# Generated by Django 5.2.4 on 2025-08-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('role', models.CharField(choices=[('父', '父'), ('母', '母'), ('息子', '息子'), ('娘', '娘'), ('おじいちゃん', 'おじいちゃん'), ('おばあちゃん', 'おばあちゃん'), ('その他', 'その他')], max_length=20, verbose_name='続柄')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='family_photos/', verbose_name='写真')),
                ('favorite_food', models.CharField(blank=True, max_length=200, verbose_name='好きな食べ物')),
                ('hobby', models.CharField(blank=True, max_length=200, verbose_name='趣味')),
                ('introduction', models.TextField(blank=True, help_text='家族への一言やメッセージを書いてください', verbose_name='自己紹介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '家族メンバー',
                'verbose_name_plural': '家族メンバー',
                'ordering': ['role', 'name'],
            },
        ),
    ]
