# Generated by Django 5.2.4 on 2025-08-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='チェックを外すと一覧に表示されません', verbose_name='表示する'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='photo',
            field=models.ImageField(blank=True, help_text='推奨サイズ: 正方形、5MB以下', null=True, upload_to='family_photos/', verbose_name='写真'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['role'], name='main_family_role_a61464_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['is_active'], name='main_family_is_acti_7f7ea2_idx'),
        ),
    ]
