# Generated by Django 5.2.4 on 2025-08-02 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_familymember_is_active_alter_familymember_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('color', models.CharField(default='#3498db', help_text='HEXカラーコード（例: #3498db）', max_length=7, verbose_name='色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': '写真タグ',
                'verbose_name_plural': '写真タグ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='アルバム名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='album_covers/', verbose_name='カバー写真')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '写真アルバム',
                'verbose_name_plural': '写真アルバム',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('image', models.ImageField(help_text='推奨サイズ: 10MB以下', upload_to='gallery/%Y/%m/', verbose_name='写真')),
                ('description', models.TextField(blank=True, verbose_name='説明・コメント')),
                ('taken_date', models.DateField(help_text='写真が撮影された日付', verbose_name='撮影日')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='撮影場所')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='お気に入り')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('family_members', models.ManyToManyField(blank=True, help_text='写真に写っている家族メンバーを選択してください', to='main.familymember', verbose_name='写っている家族')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='main.photoalbum', verbose_name='アルバム')),
                ('tags', models.ManyToManyField(blank=True, help_text='写真に関連するタグを選択してください', to='main.phototag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '家族写真',
                'verbose_name_plural': '家族写真',
                'ordering': ['-taken_date', '-created_at'],
                'indexes': [models.Index(fields=['taken_date'], name='main_family_taken_d_2678cb_idx'), models.Index(fields=['is_favorite'], name='main_family_is_favo_7b9932_idx'), models.Index(fields=['is_public'], name='main_family_is_publ_da23e8_idx'), models.Index(fields=['album'], name='main_family_album_i_21c636_idx')],
            },
        ),
    ]
