# Generated by Django 5.2.4 on 2025-08-02 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_phototag_photoalbum_familyphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
                ('emoji', models.CharField(default='📅', max_length=10, verbose_name='絵文字')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='色')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'イベントカテゴリ',
                'verbose_name_plural': 'イベントカテゴリ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='イベント名')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='終日')),
                ('repeat', models.CharField(choices=[('none', '繰り返しなし'), ('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月'), ('yearly', '毎年')], default='none', max_length=10, verbose_name='繰り返し')),
                ('repeat_until', models.DateField(blank=True, null=True, verbose_name='繰り返し終了日')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='場所')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '緊急')], default='normal', max_length=10, verbose_name='重要度')),
                ('is_reminder_enabled', models.BooleanField(default=True, verbose_name='リマインダー')),
                ('reminder_minutes', models.IntegerField(default=60, verbose_name='リマインダー時間（分前）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.eventcategory', verbose_name='カテゴリ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('participants', models.ManyToManyField(blank=True, to='main.familymember', verbose_name='参加者')),
            ],
            options={
                'verbose_name': '家族イベント',
                'verbose_name_plural': '家族イベント',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
